### ISSUE TITLE
tnt_main.c:3921 (processDescr1): Assertion 'varEnd != NULL' failed.

### ISSUE THREAD

**Issue by vanhauser-thc** [wmkhoo/taintgrind#16] opened 2018-02-21 09:17 UTC
Why I run taintgrind with a standard feature
valgrind --tool=taintgrind --file-filter='*' -- cat /etc/lsb-release
...
Taintgrind: tnt_main.c:3921 (processDescr1): Assertion 'varEnd != NULL' failed.

I can also remove file-filter and it produces the same error.

This is on valgrind 3.13 (untested on 3.12) x64

**Comment by wmkhoo** [comment] 2018-02-22 00:29
Able to reproduce this bug.
The patch seems to deal with the issue.

**Comment by vanhauser-thc** [comment] 2018-02-22 10:28
The original bug is fixed, now it crashes further down the execution:

```
./valgrind --tool=taintgrind --taint-all=yes --tainted-ins-only=yes --file-filter=/etc/lsb-release -- cat /etc/lsb-release 
[... looooots of output removed]
--16531-- warning: evaluate_Dwarf3_Expr: unhandled DW_OP_ 0xf3
--16531-- warning: evaluate_Dwarf3_Expr: unhandled DW_OP_ 0xf3
t9_9870 <- 1fff000600_unknownobj
0x4EABE9B: _IO_cleanup (genops.c:997) | r120_1510 = t9_9870 | 0x51e1d60 | 0xfffffffffffff000 | r120_1510 <- t9_9870
0x4EF36A3: _Exit (_exit.c:27) | t12_18346 = LOAD I64 0x51dfe68 | 0xffffffffffffff80 | 0xffffffffffffffff | t12_18346 <- 51dfe68_unknownobj
0x4EF36A3: _Exit (_exit.c:27) | r88_2397 = t12_18346 | 0xffffffffffffff80 | 0xffffffffffffffff | r88_2397 <- t12_18346
==16531== 
blockSane: fail -- redzone-hi

valgrind: m_mallocfree.c:2107 (vgPlain_arena_free): Assertion 'is_inuse_block(b) && blockSane(a, b)' failed.

host stacktrace:
==16531==    at 0x5802FA8A: show_sched_status_wrk (m_libcassert.c:355)

sched status:
  running_tid=1
```

**Comment by vanhauser-thc** [comment] 2018-02-26 11:27
the patch works, thanks!

I get masses of "warning: evaluate_Dwarf3_Expr: unhandled DW_OP_ 0xf3" what is up with that?

and this:
```
tnt_main.c: In function 'vgTaintgrind_h64_puti':
tnt_main.c:3167:21: warning: right shift count >= width of type [-Wshift-count-overflow]
    UInt base = (tt1 >> 32) & 0xffffffff;
                     ^~
tnt_main.c:3170:19: warning: right shift count >= width of type [-Wshift-count-overflow]
    UInt ix = (tt2 >> 32) & 0xffffffff;
                   ^~
```
seems to be an error in the code as tt1 and tt2 seem to be only 16 bit wide

**Comment by wmkhoo** [comment] 2018-02-27 00:41
Handling the PutI (and GetI) instruction is admittedly still a work-in-progress.

The Dwarf3 warnings are there due to calls to valgrind's describe_addr()/get_data_description(). From searching around, the warnings seem to be coming from the "dwarf var-loc reader".
https://sourceforge.net/p/valgrind/mailman/valgrind-developers/thread/200505241641.54642.dmuell%40gmx.net/

**Comment by wmkhoo** [comment] 2018-03-02 03:30
Closing this issue

**Closed by wmkhoo** 2018-03-02 03:30 UTC
